GrandCafe/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views

urlpatterns = [
#site root
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('',views.greet),
    path('login/',views.LoginFormView.as_view()),
    path('register/',views.RegisterFormView.as_view()),
    path('logout/',views.LogoutView.as_view()),
    path('recepts/',views.paginator),
    path('search/',include('search.urls'))

]

post/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    # post root
    #path('register/', views.RegisterFormView.as_view()),
    #path('login/', views.LoginFormView.as_view()),
    #path('logout/', views.LogoutView.as_view()),
    path(r'', views.MainView.as_view()),  # <---post root
    #path('recepts/', paginator, name="home_url"),  # <---/post/page
    path('recept/<str:slug>/', post_detail, name='post_detail_url'),  # /post/page/ReCept Slug
    path('add/', add_post, name='post_add'),  # adding post /post/add/
    path('tags/', post_tags, name='post_tags_url'),



]
# no slash before path!11111

post/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount, HitCountMixin
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30, db_index= True)
    def __str__(self):
        return '{}'.format(self.name)

class SubCategory(models.Model):
    name = models.CharField(max_length=30, db_index= True)
    category=models.ForeignKey(Category, on_delete = models.PROTECT,default=0)
    def __str__(self):
        return '{}'.format(self.name)

class Post(models.Model,HitCountMixin):
    title = models.CharField(max_length=150, db_index= True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    category = models.TextField(max_length=50, blank=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    ingredients = models.TextField(blank=False)
    cooking = models.TextField(blank=False)
    date_pub = models.DateTimeField(auto_now_add=True)
    time_cooking = models.TextField(blank=True, max_length=30)
    category = models.ForeignKey(Category, on_delete = models.PROTECT,default=0)
    subcategory=models.ForeignKey(SubCategory, on_delete = models.PROTECT,default=0)
    views = models.IntegerField(blank=False,default=0)
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')


    def ingredients_as_list(self):
        return self.ingredients.split('\n')

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        ordering = ['-date_pub']

class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return '{}'.format(self.title)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_birth = models.DateField(auto_now_add=False, auto_now=False, verbose_name='дата рождения')
    email = models.EmailField(max_length=50, verbose_name='email')

"""
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()
"""

post/forms.py
from django import forms

from .models import Post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title',
         #'slug',
         'category',#'tags',
         'ingredients','cooking','time_cooking',)

post/views.py
from django.shortcuts import render
from .models import Post, Tag, Profile
from django.views.generic.base import View
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import logout,login
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator
from django.db.models import F
from .forms import PostForm
from uuslug import slugify
# Create your views here.


def greet(request):
	return render(request,'post/greet.html')

class MainView(TemplateView):
	template_name = 'post/blank.html'
	def get(self, request):
		if request.user.is_authenticated:
			humans = Human.objects.all()
			ctx = {}
			ctx['humans'] = humans
			return render(request, self.template_name, ctx)
		else:
			return render(request, self.template_name, {})

class RegisterFormView(FormView):
	form_class = UserCreationForm
	success_url = "/post/login/"

	template_name = "post/register.html"


	def form_valid(self, form):
		form.save()
		return super(RegisterFormView, self).form_valid(form)
	def form_invalid(self, form):

		return super(RegisterFormView, self).form_invalid(form)

class LoginFormView(FormView):
	form_class = AuthenticationForm

	template_name = "post/login.html"

	success_url = "/recepts/"
	def form_valid(self, form):
		self.user = form.get_user()

		login(self.request, self.user)
		return super(LoginFormView, self).form_valid(form)

class LogoutView(View):
	def get(self, request):
		logout(request)
		return HttpResponseRedirect("/")





def paginator(request):
	posts = Post.objects.all()
	paginator = Paginator(posts, 10)

	page_number = request.GET.get('page', 1)
	page = paginator.get_page(page_number)


	is_paginated = page.has_other_pages()
	if page.has_previous():
		prev_url='?page={}'.format(page.previous_page_number())
	else:
		prev_url = ''

	if page.has_next():
		next_url='?page={}'.format(page.next_page_number())
	else:
		next_url=''
	context= {'page_object':page,
	             'is_paginated':is_paginated,
				 'next_url':next_url,
				 'prev_url':prev_url
	}
	return render(request,'post/index.html', context=context)

def post_detail(request, slug):
	post = Post.objects.get(slug__iexact=slug)
	Post.objects.filter(slug__iexact=slug).update(views=F('views')+1)
	return render(request, 'post/post_detail.html',context={'post':post})

def add_post(request):
    #print(request)
    #print(dir(request))
    print(*request.POST)
    #print(request.method)
    if request.method == "POST":
        form = PostForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            post = form.save(commit=False)
            post.title = request.POST["title"]
            post.slug = slugify(request.POST["title"])
            link=slugify(request.POST["title"])
            #post.category = category.filter(id__iexact=request.POST["category"]).get('name')
            #post.tags = request.POST["tags"]
            post.ingredients = request.POST["ingredients"]
            post.cooking = request.POST["cooking"]
            post.time_cooking = request.POST["time_cooking"]
            post.save()
            return HttpResponseRedirect("/post/recept/"+link)
    else:
        form = PostForm()
    return render(request, 'post/add.html', {'form': form})

def post_tags(request):
	tags = Tag.objects.all()
	return render(request, 'post/tag_post.html',context={'tags':tags})

post/templates/post/add.html
{% extends 'base.html' %}

{% block head %}
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style type="text/css">
 {% block styles %}


body{
  background:url(https://cdn.pixabay.com/photo/2015/10/02/15/59/olive-oil-968657_960_720.jpg)no-repeat center center fixed;
        background-size: cover;
        }

#form-add{
  display:flex;
  flex-direction:column;
  align-items:center;
 margin-left:300px;
 margin-right:250px;
margin-top:90px;
margin-bottom:80px;
}


#id_title{
    margin-left:53px;
}

textarea{
  width:400px;
  height:200px;
  border-radius:5px;
}



#id_category{
  width:200px;
  border-radius:4px;
}

#id_tags{
  width:200px;
  height:40px;
  margin-left:50px;
  border-radius:4px;
}

#id_ingredients{
  margin-left:17px;
}

#id_cooking{
    margin-left:42px;
}

#button-add{
  margin-left:220px;
}



  </head>
  {% endblock %}
  </style>
   {% endblock %}


{% block content %}
<body>
<form method="post" action="{% url 'post_add' %}" class="form__add"> {% csrf_token %}
  <div class="col-sm-6" id="form-add">
  <div class="card border-dark form__add__card">
      <div class="card-header bg-dark text-light text-center form__add__header">Добавление рецепта</div>
  <div class="card-body bg-warning form__add__card__body"  style="width: 38rem;">

    <div class="input-group mb-3  form__add__title">
  <div class="input-group-prepend">
   <label class="input-group-text text-dark form__add__label" for="inputGroupSelect01">Название рецепта</label>
  </div>
  <input type="text" class="form-control form__add__input" placeholder="" name="title" aria-label="Example text with button addon" aria-describedby="button-addon1">
</div>


  <div class="input-group mb-3 form__add__time">
  <div class="input-group-prepend">
    <label class="input-group-text text-dark form__add__label" for="inputGroupSelect01">Время</label>
  </div>
  <select class="custom-select form__add__custom" id="inputGroupSelect01" name="time_cooking">
    <option selected>до 30 минут</option>
    <option value="около часа">около часа</option>
    <option value="1.5 часа">1.5 часа</option>
    <option value="2 часа">2 часа</option>
     <option value="3 часа">3 часа</option>
  </select>
</div>

<div class="input-group mb-3 form__add__category">
  <div class="input-group-prepend">
    <label class="input-group-text text-dark form__add__label" for="inputGroupSelect01">Категория</label>
  </div>
  <select class="custom-select form__add__custom" id="inputGroupSelect01" name="category">
    <option selected value="0">Без категории</option>
    <option value="1">Первое блюдо</option>
    <option value="2">Второе блюдо</option>
    <option value="3">Закуски</option>
    <option value="4">Выпечка</option>
    <option value="5">Десерты</option>
    <option value="6">Напитки</option>
     <option value="7">Соусы</option>
  </select>
</div>


<div class="input-group mb-3 form__add__tags">
  <div class="input-group-prepend">
   <label class="input-group-text text-dark form__add__label" for="inputGroupSelect01">Тэги</label>
  </div>
  <input type="text" class="form-control form__add__input" placeholder="" name="tags" aria-label="Example text with button addon" aria-describedby="button-addon1">
</div>


  <div class="form-group form__add__image">
    <label for="exampleFormControlFile1" class="form__add__label">Добавить картинку</label>
    <input type="file" class="form-control-file" id="exampleFormControlFile1">
  </div>


  <div class="form-group form__add__ingredients">
    <label for="exampleFormControlTextarea1" class="form__add__label">Ингредиенты</label>
    <textarea class="form-control form__add__textarea" id="exampleFormControlTextarea1" name="ingredients" rows="3"></textarea>
  </div>


<div class="form-group form__add__cooking">
    <label for="exampleFormControlTextarea1" class="form__add__label">Приготовление</label>
    <textarea class="form-control form__add__textarea" id="exampleFormControlTextarea1" name="cooking"  rows="3"></textarea>
  </div>


<button type="submit" class="btn btn-outline-primary form__add__button">Добавить</button>

    </div>
  </div>
</div>
</form>
    </body>
{% endblock %}

post/templates/post/base_templ.html
{% extends 'base.html' %}

post/templates/post/blank.html
<html>
<title>Title</title>
<head>
  <style>

      a{
        display: block;
        float: right;
        margin-right: 25px;
        padding: 10px 50px;
        color: black;

        border-radius: 15px;
        border: 1px solid black;
        text-decoration: none;
        transition: color 0.5s , background 0.5s
      }

      a:hover{
        color: black;
        background: blue;
        border: 1px solid blue;
        text-decoration: none;
      }
  </style>
</head>

<body>
{% if user.is_authenticated %}
<a href="logout">выйти({{user.username}})</a>
{% else %}
<a href="register">Регистрация на сайте</a>
<a href="login">Авторизация</a>
{% endif %}

{% for elem in humans %}
<p>{{elem.name}}</p>
<p>{{elem.surname}}</p>
<p>{{elem.login}}</p>
{% endfor %}
</body>
</html>

post/templates/post/greet.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lora:400,700">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}

{% block styles %}
@font-face {
  font-family: Rakkas;
  src: url(fonts/rakkas.ttf);
}

body{
  background:rgb(255,87,87);
  font-family: Roboto;
    color:white;
}

h5{
  color:yellow;
}

.first-level{
  display:flex;
  flex-direction:row;
  justify-content:space-around;
}

.carousel-slide{
  margin-top:220px;
  width:620px;
  height:417px;
  border:7px solid yellow;
  margin-left:40px;
  margin-bottom:30px;
}

.first-level-main-title{
  font-family: Cantarell Extra Bold;
  font-style:normal;
      font-size: 600%;
      color:yellow;
      padding:100p;
}
.first-level-subtitle{
  font-size: 20px;
  color:white
}
.first-level-rightplace{
  margin-top:200px;
}

.first-level-left{
  margin-top:130px;
  border: 7px solid yellow;
}

.first-level-link{
  color:yellow;
  margin-top:230px;
  margin-left: 270px;
  border:1px solid yellow;
  border-radius: 30px;
  text-align:center;
  width:280px;
  height:50px;
  text-decoration:none;
  font-size:30px;
}


.first-level-link:hover{
  background:white;
  color:red;
  text-decoration:none;
}

.first-level-border{
  display:flex;
  border: 4px solid yellow;
  border-radius: 5px;
  justify-content:center;
  margin-top:40px;
  margin-left:35px;
  margin-right:35px;
  margin-bottom:30px;
}


.second-level{
  display:flex;
  flex-direction:row;
  flex-wrap:nowrap;
  justify-content:space-around;
  margin-right:110px;

}

.second-level-leftplace{
  width:200px;
  height:200px;
}
.second-level-middleplace{
  width:200px;
  height:200px;
}
.second-level-rightplace{
  width:200px;
  height:200px;
}

.second-level-picture{
  border: 3px solid rgb(255, 237, 0);
  align-items:flex-start;
  margin-bottom:20px;
  width:330;
  height:150;
}

.second-level-picture:hover{
  border:rgb(255,87,87);
}

.second-level-headline{
  color:#fef102;
  font-size: 16px;
  font-style:bold;
}

.second-level-headline-2{
  color:#fef102;
}

.second-level-border{
  display:flex;
  border: 4px solid yellow;
  border-radius: 5px;
  justify-content:center;
  margin-top:350px;
  margin-left:35px;
  margin-right:35px;
  margin-bottom:30px;
}

.third-level{
  display:flex;
  flex-direction:row;
  flex-wrap:nowrap;
  justify-content:space-around;
  margin-left:30px;
}

.third-level-leftplace{
  width:535px;
  height:535px;
}

.third-level-rightplace{
  width:535px;
  height:535px;
}

.third-level-picture{
    border: 4px solid rgb(255, 237, 0);
    align-items:flex-start;
    margin-bottom:20px;
  }

  .third-level-picture:hover{
    border:rgb(255,87,87);
  }


.third-level-leftplace-headline{
  color:#fef102;
}

.third-level-border{
  display:flex;
  border: 4px solid yellow;
  border-radius: 5px;
  justify-content:center;
  margin-left:35px;
  margin-right:35px;
  margin-bottom:30px;
}

.new-recepts-headline{
  margin-left:50px;
  margin-bottom:15px;
  color:#fef102;
}

.fourth-level{
  display:flex;
  flex-direction:row;
  flex-wrap:nowrap;
  justify-content:space-around;
  margin-left:20px;
  margin-bottom:30px;
}

.fourth-level-picture{
  border: 4px solid rgb(255, 237, 0);
  margin-bottom:10px;
}

.fourth-level-picture:hover{
  border:rgb(255,87,87);
}

.fourth-level-border{
  display:flex;
  border: 4px solid yellow;
  border-radius: 5px;
  justify-content:center;
  margin-left:35px;
  margin-right:35px;
  margin-bottom:30px;
}

.fifth-level{
  display:flex;
  flex-direction:row;
  flex-wrap:nowrap;
  justify-content:space-around;
  margin-left:40px;
}

.fifth-level-news-headline-1{
  width:435px;
  height:535px;
  margin-right:30px;
  color:white;
}

.fifth-level-news-headline-1 > h5{
  color:white;
}


.fifth-level-news-headline-2{
  width:485px;
  height:535px;
  margin-right:30px;
}

.fifth-level-news-headline-2 > h5{
  color:white;
}

.fifth-level-news-headline-3{
  width:485px;
  height:535px;
  margin-right:30px;
}

.fifth-level-news-headline-3 > h5{
  color:white;
}

.fifth-level-news-headline-4{
  width:485px;
  height:535px;
  margin-right:30px;
}

.news-for-fifth-level{
  margin-left:40px;
  color:#fef102;
}



    {% endblock %}
      {% block content %}
      <div class="first-level">
          <div class="first-level-left-carousel">
            <div id="carouselExampleSlidesOnly" class="carousel-slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="https://s15.stc.all.kpcdn.net/share/i/12/10608869/inx960x640.jpg"  alt="Первый слайд">
                    </div>
                  <div class="carousel-item">
                <img class="d-block w-100" src="https://www.learnathome.ru/files/media/food.jpg" alt="Второй слайд">
              </div>
            <div class="carousel-item">
          <img class="d-block w-100" src="https://vibirai.ru/image/1452843.w640.jpg" alt="Третий слайд">
        </div>
      </div>
    </div>
  </div>

<div class="first-level-rightplace">
  <h1 class="first-level-main-title">GrandCafe</h1>
      <p class="first-level-subtitle">Сборник рецептов с миру по нитке</p>
        <div class="first-level-link"><a href="/recepts/"> Перейти ➞ </a></div>
          </div>
              </div>
<div class="first-level-border"></div>



               <div class="second-level">
                    <div class="second-level-leftplace">
                     <p class="second-level-headline">Рецепт дня</p>
                      <img class="second-level-picture" src="https://www.gastronom.ru/binfiles/images/20170218/md8488bb.jpg" alt="" width="330" height="200">
                            <h5 class="second-level-headline-2">Простые сырники</h5>
                                <p>Сырниками в России назывались не только всем известные творожные лепешки, но и большие, во всю сковороду, творожные запеканки. А еще - пироги с творогом. Мы сейчас говорим именно о классике</p>
                                    </div>

                   <div class="second-level-middleplace">
                     <p class="second-level-headline">Экономим время и деньги</p>
                        <img class="second-level-picture" src="https://www.gastronom.ru/binfiles/images/20190522/b5f359d7.jpg" alt="" width="330" height="200">
                          <h5 class="second-level-headline-2">Глазунья со шпинатом и брокколи</h5>
                              <p>Глазунья со шпинатом и брокколи с утра  - просто, быстро, вкусно и ооочень полезно.</p>
                               </div>

                    <div class="second-level-rightplace">
                      <p class="second-level-headline">Ризи бизи</p>
                          <img class="second-level-picture" src="https://www.gastronom.ru/binfiles/images/20190416/bb68a08b.jpg" alt="" width="330" height="200">
                              <p>Это самое популярное блюдо Венеции готовится легко и просто, а результат всегда замечательный. По традиции региона Венето ризотто подаются аль-ондо, буквально «на волне», то есть в них ...</p>
                                  </div>
                                      </div>
          <div class="second-level-border"></div>



<div class="third-level">
    <div class="third-level-leftplace">
         <img class="third-level-picture" src="https://www.gastronom.ru/binfiles/images/20160615/b8baa5d7.jpg" width="530" height="320" alt="">
            <h5 class="third-level-leftplace-headline">8 идей летней заморозки</h5>
              <p>Лето – лучшее время, чтобы проверить вашу морозильную камеру. Ведь в ней можно хранить не только рыбу и мясо, но и достаточный запас ледяных кубиков для напитков, полезное мороженое и замороженные ягоды</p>
                </div>

<div class="third-level-rightplace">
    <img class="third-level-picture" src="https://www.gastronom.ru/binfiles/images/20190520/bb962401.jpg" width="530" height="320" alt="">
        <h5 class="third-level-leftplace-headline">Готовим яркие зеленые супы</h5>
            <p>Зеленые супы готовят из молодой зелени – крапивы, щавеля, свекольной ботвы, шпината, руколы и даже одуванчика. Лучшее время для зеленых супов – май и начало лета.</p>
               </div>
                   </div>
<div class="third-level-border"></div>


<h3 class="new-recepts-headline">Новые рецепты</h3>


<div class="fourth-level">
    <div class="fourth-level-1"><img class="fourth-level-picture" src="https://www.gastronom.ru/binfiles/images/20190530/b742cae8.jpg" alt="" width="250" height="160"><p>Крылышки в азиатской карамели</p></div>
      <div class="fourth-level-2"><img class="fourth-level-picture" src="https://www.gastronom.ru/binfiles/images/20190530/m53ff0cc.jpg" alt="" width="250" height="160"><p>Классические крылышки баффало</p></div>
        <div class="fourth-level-3"><img class="fourth-level-picture" src="https://www.gastronom.ru/binfiles/images/20190530/m047ac99.jpg" alt="" width="250" height="160"><p>Торт с ягодным кремом</p></div>
          <div class="fourth-level-4"><img class="fourth-level-picture" src="https://www.gastronom.ru/binfiles/images/20190530/m9e94a1c.jpg" alt="" width="250" height="160"><p>«Ангельский бисквит»</p></div>
            </div>
<div class="fourth-level-border"></div>



<h3 class="news-for-fifth-level">Новости</h3>
  <div class="fifth-level">
    <div class="fifth-level-news-headline-1"> <h5>Выбираем самое лучшее мороженое вместе с Роскачеством</h5> <h5>...</h5><h5>Скоро в продаже появится хлеб с минимумом соли</h5> <h5>...</h5><h5>Названы самые эффективные средства для мытья посуды</h5> <h5>...</h5></div>
     <div class="fifth-level-news-headline-2"><h5>Даёшь сдачу стеклотары!</h5> <h5>...</h5> <h5>У почти половины жителей России денег хватает только на еду и одежду</h5> <h5>...</h5><h5>Ананасовый сок улучшает обмен веществ. Доказано!</h5> <h5>...</h5></div>
      <div class="fifth-level-news-headline-3"><h5>Atelier de Tartelettes – новая кондитерская-магазин на Патриарших прудах</h5> <h5>...</h5> <h5>Белые ночи, вкусные дни: в Петербурге пройдет фестиваль Gourmet Days</h5> <h5>Мексиканская кухня новой волны в Community</h5> <h5>...</h5> </div>
       <div class="fifth-level-news-headline-4"></div>
          </div>


      {% endblock %}

post/templates/post/index.html
{% extends 'base.html' %}
  {% block head %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% endblock %}
  <style>
  {% block styles %}

body{
  background:rgb(255,87,87);
  margin-top:100px;
}
    .flex-container{
    display: flex;
    flex-flow: row wrap;
    justify-content:center;

  }

  .item {
    flex-basis: 25%;
    font-size: 14px;
    margin: 10px;
  }


  .paginator{
      display: flex;
    justify-content:center;
    margin-top:40px;
    margin-bottom:20px;
    padding-top:10px;
  }

.col-md-8:hover{
  background:rgb(137, 246, 28);
}

.item:hover{
  width: 25rem;

}

.card-img{
  border:1px solid black;
}

.card-img:hover{
border:1px solid red;
}

  {% endblock %}

</style>

{% block tilte %}
Start page
{% endblock %}

{% block content %}





<div class="flex-container">
  {% for post in page_object.object_list %}
  <div class="item">
    <div class="card bg-light mb-3 border-dark" style="max-width:430px;">
      <div class="row no-gutters">
        <div class="col-md-4 ">
          <img src="http://xn--80aaa5athr.xn--p1ai/wp-content/uploads/2017/11/1%D0%B0%D0%BD%D0%B8-300x300.jpg" class="card-img" alt="..." >
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text text-dark">{{ post.ingredients | truncatewords:6}}</p>
             <p class="card-text text-dark">{{ post.cooking | truncatewords:12}}</p>
             <p class="card-text">{{ post.date_pb }}</p>
             <p class="card-text"><small class="text-muted">{{ post.time_cooking }}</small></p>
          <div class="text-right"> <a href="{% url 'post_detail_url' slug=post.slug %}" class="btn btn-info btn-sm btn-block" role="button">Перейти</a></div>
          </div>
        </div>
      </div>
    </div>
</div>
  {% endfor %}
</div>


{% if is_paginated %}
<div class="paginator">
<nav aria-label="..." >
  <ul class="pagination">
    <li class="page-item {% if not prev_url %} disabled {% endif %}">
      <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Предыдущая</a>
    </li>

    {% for n in page_object.paginator.page_range %}
    {% if page_object.number == n %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="?page={{ n }}">{{ n }} <span class="sr-only">(current)</span></a>
    </li>
    {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
    <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
    {% endif %}
    {% endfor %}

    <li class="page-item {% if not next_url %} disabled {% endif %}">
      <a class="page-link" href="{{next_url}}" tabindex="-1" aria-disabled="true">Следующая</a>
    </li>
  </ul>
</nav>
  </div>
  {% endif %}



{% endblock %}

post/templates/post/tag_post.html
{% block content %}

<h1>Tags:</h1>

{% for tag in tags %}
<h3>{{ tag.title }}</h3>
{% endfor %}

{% endblock %}